apiVersion: apps/v1
kind: Deployment
metadata:
  name: nyu-devops-recommendation
  labels:
    app: nyu-devops-recommendation
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: nyu-devops-recommendation
  template:
    metadata:
      labels:
        app: nyu-devops-recommendation
    spec:
      imagePullSecrets:
      - name: all-icr-io
      restartPolicy: Always
      containers:
      - name: nyu-devops-recommendation
        image: us.icr.io/yjlo/nyu-devops-recommendation:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: postgres-creds
                key: database_uri
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 30
          httpGet:
            path: /health
            port: 8080
        resources:
          limits:
            cpu: "0.20"
            memory: "64Mi"
          requests:
            cpu: "0.10"        
            memory: "32Mi"